-- ============================================================
-- HRP Website — Product Descriptions
-- Sets description for all 103 products, matched by slug.
-- Safe to re-run any time: UPDATE only, no inserts/deletes.
-- Edit any description text below and re-run to apply changes.
-- Run in: Supabase → SQL Editor → New Query → Run
-- ============================================================

UPDATE products SET description = v.description
FROM (VALUES

  -- ── Hydraulics ─────────────────────────────────────────────
  ('hydraulic-cylinders', 'Double-acting and single-acting hydraulic cylinders for presses, material handling and mobile equipment. Available in tie-rod, welded and mill-duty constructions with bore sizes from 25 mm to 300 mm, honed tubes and hard-chrome plated rods for long seal life.'),
  ('hydraulic-motors', 'Gear, vane and orbital hydraulic motors delivering high torque at low speeds for conveyors, winches, augers and industrial drives. Wide displacement range with smooth low-speed operation and heavy-duty shaft bearings for radial load applications.'),
  ('rotary-actuators', 'Rack-and-pinion and vane-type hydraulic rotary actuators for precise angular positioning of dampers, valves and indexing tables. Standard rotations of 90, 180 and 360 degrees with adjustable end stops and high holding torque.'),
  ('directional-control-valves', 'Spool-type directional control valves in monoblock and sectional designs for directing hydraulic flow to actuators. Manual lever, solenoid and pilot-operated versions up to 350 bar, in 4/3, 4/2 and 3/2 configurations with open, closed and tandem centre spools.'),
  ('pressure-control-valves', 'Relief, reducing, sequence and counterbalance valves for protecting hydraulic circuits and managing system pressure. Direct-acting and pilot-operated designs with fine adjustability, stable regulation and pressure ratings up to 350 bar.'),
  ('flow-control-valves', 'Needle, throttle and pressure-compensated flow control valves for regulating actuator speed in hydraulic circuits. Fine metering control with reverse free-flow check options, in threaded and flanged connections.'),
  ('proportional-servo-valves', 'Proportional and servo valves for electro-hydraulic control of pressure, flow and direction in closed-loop systems. High-resolution spools, fast response times and integrated electronics for motion control, presses and test rigs.'),
  ('hydraulic-hoses', 'Wire-braided and spiral-reinforced hydraulic hoses per SAE 100 R1, R2, 4SP and 4SH standards. Abrasion-resistant covers, temperature range from -40 to +100 degrees C, supplied cut to length or as crimped assemblies with tested end fittings.'),
  ('hydraulic-fittings-adaptors', 'Carbon steel and stainless hydraulic fittings and adaptors in BSP, NPT, JIC, ORFS and metric standards. Elbows, tees, straight connectors, bulkheads and swivels with 37-degree flare, 24-degree cone and O-ring face seal ends.'),
  ('hydraulic-quick-disconnect', 'Quick release couplings for rapid connection of hydraulic lines without tools. Poppet and flat-face designs in ISO A, ISO B and ISO 16028 profiles, with steel and stainless bodies, dust caps and pressure ratings up to 350 bar.'),
  ('hydraulic-flanges-clamps', 'SAE split flanges, weld flanges and pipe clamps for leak-free high-pressure hydraulic connections. Code 61 and Code 62 patterns with O-ring sealing, plus polypropylene and aluminium pipe clamps for tube routing and vibration control.'),
  ('hydraulic-filters-elements', 'Suction, return-line, pressure-line and off-line filters with replaceable elements for hydraulic contamination control. Glass-fibre and cellulose media from 3 to 25 micron, clogging indicators and bypass valves to protect pumps and valves.'),
  ('oil-coolers-heat-exchangers', 'Air-blast and shell-and-tube oil coolers for dissipating heat from hydraulic and lubrication systems. Aluminium plate-fin and copper-tube constructions with AC and DC fan options, sized for flow rates from 10 to 500 LPM.'),
  ('hydraulic-fluids-lubricants', 'Premium hydraulic oils, anti-wear fluids and industrial lubricants in ISO VG 32, 46 and 68 grades. High viscosity index, excellent oxidation stability and anti-foam additives for consistent performance across operating temperatures.'),

  -- ── Pneumatics ─────────────────────────────────────────────
  ('round-body-tie-rod-cylinders', 'Round-body and tie-rod pneumatic cylinders per ISO 6432 and ISO 15552 standards. Bore sizes from 8 mm to 320 mm, single and double acting, with magnetic pistons for sensor mounting, adjustable cushioning and corrosion-resistant hard-anodised barrels.'),
  ('compact-flat-body-cylinders', 'Compact and flat-body cylinders for tight installation spaces in jigs, fixtures and automation. Short overall lengths with full force output, through-hole and thread mounting, magnetic pistons and bores from 12 mm to 100 mm.'),
  ('rodless-cylinders-braided', 'Rodless cylinders and mechanically-coupled linear actuators for long strokes in compact envelopes. Magnetic and mechanical coupling designs with integrated guide rails for pick-and-place gantries, door operation and web handling.'),
  ('pneumatic-rotary-actuators', 'Rack-and-pinion and vane-type pneumatic rotary actuators plus parallel and angular air grippers. Rotations of 90 to 270 degrees, adjustable stops, and gripper jaws with sensing slots for pick-and-place and part-orientation tasks.'),
  ('pneumatic-solenoid-valves', 'Direct-acting and pilot-operated solenoid valves in 2/2, 3/2, 5/2 and 5/3 configurations. Coil voltages of 24V DC and 230V AC, manual overrides, and body ports from M5 to 1/2 inch for machine automation and process air control.'),
  ('air-pilot-mechanical-valves', 'Air-pilot, roller-lever, push-button and foot-operated valves for control circuits without electrical supply. Rugged spool and poppet constructions in 3/2 and 5/2 functions for interlocking, sensing and manual machine operation.'),
  ('valve-manifolds-islands', 'Valve manifolds and island systems for centralised pneumatic control with reduced tubing. Individual and common exhaust options, multi-pin and fieldbus connectivity, and hot-swappable valve stations for flexible machine building.'),
  ('pneumatic-flow-check-valves', 'Flow control valves with swivel fittings for cylinder speed regulation, plus inline check valves for backflow prevention. Meter-in and meter-out designs with push-to-connect ends and precise needle adjustment.'),
  ('air-filters-water-separators', 'Compressed air filters and water separators removing particulates, condensate and oil aerosols. Elements from 40 micron general purpose to 0.01 micron coalescing grades, with auto-drain options and differential pressure indicators.'),
  ('pneumatic-pressure-regulators', 'Diaphragm and piston pressure regulators for stable downstream air pressure regardless of supply fluctuation. Relieving designs with lockable knobs, gauge ports and precision versions for instrumentation duty.'),
  ('air-lubricators', 'Mist and micro-fog lubricators delivering metered oil to air tools, cylinders and valves. Adjustable drip rates, polycarbonate bowls with metal guards, and modular connection to matching filters and regulators.'),
  ('modular-frl-combo-units', 'Modular filter-regulator-lubricator combinations for complete air preparation at the point of use. Two and three-unit assemblies with mounting brackets, auto drains, pressure gauges and interchangeable modular clamps.'),
  ('push-to-connect-fittings', 'One-touch push-to-connect fittings for instant tube connection in pneumatic systems. Straight, elbow, tee, Y and function fittings for tube sizes 4 to 16 mm, with nickel-plated brass bodies and positive tube grip collets.'),
  ('threaded-fittings-adaptors', 'Brass, steel and stainless threaded fittings in BSP, NPT and metric threads for pneumatic and fluid lines. Hex nipples, sockets, elbows, tees, reducers and plugs with machined sealing faces for reliable assembly.'),
  ('pneumatic-tubing', 'Polyurethane, nylon and PTFE tubing for pneumatic circuits in standard and flame-retardant grades. Metric and imperial sizes from 4 to 16 mm OD, high flexibility, kink resistance and colour options for circuit identification.'),
  ('pneumatic-quick-disconnect', 'Quick disconnect couplings for air lines with single-hand operation. European, US industrial and Japanese profiles in steel and brass, with one-way and two-way shut-off designs for tool changeover and service points.'),
  ('pneumatic-silencers', 'Sintered bronze, plastic and stainless exhaust silencers reducing valve and cylinder exhaust noise. Standard, flat and adjustable-restrictor designs in M5 to 1 inch threads, dropping noise levels by up to 30 dB.'),
  ('pneumatic-pressure-gauges', 'Dial and digital pressure gauges and switches for monitoring pneumatic systems. Bourdon-tube and diaphragm sensing, panel and inline mounting, with switching outputs for machine interlocks and alarms.'),
  ('air-blow-guns-nozzles', 'Ergonomic air blow guns with venturi and safety nozzles for cleaning, drying and debris removal. High-thrust and noise-reduced nozzle options, OSHA-compliant dead-end pressure limiting and hanging hooks for workstation use.'),
  ('air-compressors-storage-tanks', 'Reciprocating and screw air compressors with matched storage tanks for workshop and industrial supply. Single and two-stage designs from 1 to 20 HP, pressure switches, safety valves and receiver tanks from 50 to 1000 litres.'),

  -- ── Valves ─────────────────────────────────────────────────
  ('ball-valves', 'Ball valves in one-piece, two-piece, three-piece and flanged constructions for positive shut-off. Brass, carbon steel and SS316 bodies with PTFE seats, full-bore design, and options for gas service, mini sizes and ISO actuator mounting pads.'),
  ('butterfly-valves', 'Wafer and lug pattern butterfly valves for water, air and slurry isolation. Cast iron bodies with EPDM or nitrile liners, SS discs, and lever or gear operation in sizes from 40 mm to 600 mm, with actuation-ready top flanges.'),
  ('plug-valves', 'Lubricated and sleeved plug valves for quick quarter-turn shut-off in process lines. Tapered plug design with positive sealing on viscous and dirty media, in threaded and flanged ends up to 150 mm.'),
  ('gate-valves', 'Rising and non-rising stem gate valves for full-flow isolation of water, oil and steam. Cast iron, cast steel and SS constructions with flexible wedge or solid wedge discs, flanged and screwed ends per IS, BS and API standards.'),
  ('globe-valves', 'Globe valves for throttling and regulation duty with renewable seats and discs. Straight and angle patterns in bronze, cast steel and stainless, with bolted bonnets, rising stems and pressure classes up to PN40.'),
  ('needle-valves', 'Precision needle valves for fine flow metering in instrument and hydraulic lines. Bar-stock brass, carbon steel and SS316 bodies with metal-to-metal seats, fine-pitch stems and pressure ratings up to 400 bar.'),
  ('check-valves', 'Spring-loaded and swing check valves preventing reverse flow in pipelines. Horizontal and vertical mounting designs in brass, cast iron and stainless, with soft and metal seat options from 15 mm to 300 mm.'),
  ('foot-valves', 'Foot valves with integral strainers for pump suction lines, maintaining prime and blocking debris. Cast iron, bronze and PVC bodies with rubber or metal seats, in screwed and flanged ends for bore-well and sump duty.'),
  ('safety-relief-valves', 'Spring-loaded safety and relief valves protecting vessels, compressors and boilers from overpressure. Open and closed bonnet designs with test levers, set pressures certified on request, in bronze, CS and SS trims.'),
  ('pressure-reducing-valves', 'Self-acting pressure reducing valves maintaining constant downstream pressure for steam, air and water. Diaphragm and piston operated with adjustable set ranges, strainer screens and balanced seat designs for stable control.'),
  ('pilot-operated-pressure-regulators', 'Pilot-operated regulators for precise pressure control on high flow rates where direct-acting valves fall short. External pilot lines, quick response to demand swings and tight deadband for process stability.'),
  ('sanitary-hygienic-valves', 'Sanitary butterfly, ball and seat valves in SS316L for food, dairy and pharma processing. Tri-clover clamp ends, crevice-free internals, FDA-grade seals and polished contact surfaces to 0.5 Ra for CIP and SIP service.'),
  ('diaphragm-valves', 'Weir and straight-through diaphragm valves isolating corrosive and abrasive media from working parts. Rubber-lined and unlined bodies with EPDM, PTFE and butyl diaphragms for slurry, chemical and water treatment duty.'),
  ('pinch-valves', 'Pinch valves with full-bore elastomer sleeves for slurries, powders and granular media. Manual, pneumatic and flanged designs where the sleeve is the only wetted part, giving zero dead space and easy sleeve replacement.'),

  -- ── Instrumentation ────────────────────────────────────────
  ('pressure-gauges', 'Bourdon-tube pressure gauges in dial sizes from 50 to 250 mm for utility and process duty. Brass and SS316 internals, glycerine filling for vibration damping, and ranges from vacuum to 1000 bar with IS and EN accuracy classes.'),
  ('pressure-transmitters-transducers', 'Pressure transmitters and transducers converting process pressure to 4-20 mA, 0-10 V and digital outputs. Piezoresistive and thin-film sensors, SS wetted parts, accuracies to 0.25 percent FS and HART options for smart integration.'),
  ('differential-pressure-instruments', 'Differential pressure gauges, switches and transmitters for filter monitoring, flow and level applications. Dual-port designs with magnehelic-style, piston and diaphragm sensing across mbar to bar ranges.'),
  ('pressure-switches', 'Mechanical and electronic pressure switches with adjustable setpoints and switching differentials. SPDT and DPDT contacts, IP65 enclosures, and diaphragm or piston sensing for pump control, alarms and safety interlocks.'),
  ('thermocouples-rtd', 'Thermocouples in J, K, T and N types plus PT100 RTD sensors for industrial temperature measurement. Mineral-insulated and fabricated constructions with heads, extension leads and calibration certificates on request.'),
  ('temperature-transmitters', 'Head-mount, rail-mount and field-mount temperature transmitters converting RTD and thermocouple signals to 4-20 mA. Galvanic isolation, sensor break detection and HART configurable ranges for reliable plant integration.'),
  ('bimetal-digital-thermometers', 'Bimetal dial thermometers and digital indicators for local temperature display. Every-angle and back-entry stems, dial sizes 63 to 150 mm, ranges from -50 to +500 degrees C with recalibratable movements.'),
  ('thermowells', 'Machined barstock thermowells protecting temperature sensors from process media. Threaded, flanged and weld-in designs in SS316, SS304 and exotic alloys, with tapered and straight bores manufactured to sensor insertion lengths.'),
  ('rotameters-variable-area-flow-meters', 'Glass-tube and metal-tube variable area flow meters for liquids and gases. Direct-reading scales, needle valve options, and SS float designs with local pointers or 4-20 mA transmitters for flow indication and control.'),
  ('digital-flow-meters', 'Electromagnetic, turbine and oval-gear digital flow meters with rate and totaliser displays. Pulse and 4-20 mA outputs, battery and loop-powered options, for water, fuels, chemicals and viscous fluids.'),
  ('mass-flow-controllers', 'Thermal mass flow controllers and meters for precise gas flow measurement independent of pressure and temperature. Ranges from sccm to Nm3/hr with fast control valves, digital communication and calibration for common process gases.'),
  ('flow-switches', 'Paddle, thermal and piston flow switches protecting pumps and circuits from loss of flow. Adjustable setpoints, SPDT outputs and brass or SS wetted parts for water, oil and gas lines from 15 mm upward.'),
  ('level-switches', 'Float, vibrating-fork and conductivity level switches for point level detection in tanks and hoppers. Side and top mounting, high and low alarm duty, with wide media compatibility and IP65 terminations.'),
  ('level-transmitters-sensors', 'Hydrostatic, ultrasonic and radar level transmitters for continuous level measurement of liquids and solids. 4-20 mA and HART outputs, ranges to 30 m, with flanged, threaded and cable-suspended process connections.'),
  ('analytical-sensors', 'pH, conductivity, dissolved oxygen and turbidity sensors for water treatment and process analytics. Industrial-grade electrodes with automatic temperature compensation and transmitters offering relay and current outputs.'),
  ('hand-pumps-pressure-calibrators', 'Hand-operated pressure and vacuum pumps with precision test gauges for field calibration. Generate up to 700 bar hydraulically or 40 bar pneumatically, with fine-adjust vernier, test hoses and adaptor kits.'),
  ('dry-block-temperature-calibrators', 'Dry-block calibrators for verifying temperature sensors from -25 to +650 degrees C. Fast heating and cooling, stability to 0.05 degrees, interchangeable inserts and documenting versions with reference probe inputs.'),
  ('multimeters-loop-calibrators', 'Process multimeters and loop calibrators sourcing and measuring 4-20 mA, voltage, frequency and RTD signals. HART loop power, simultaneous source-measure modes and rugged field cases for commissioning and troubleshooting.'),

  -- ── Rubber Products ────────────────────────────────────────
  ('industrial-rubber-sheeting', 'Industrial rubber sheeting in neoprene, nitrile NBR, EPDM, silicone and viton grades. Thicknesses from 1 to 50 mm in plain, cloth-inserted and food-quality finishes, supplied in rolls and cut pads for gasketing and lining.'),
  ('anti-fatigue-ergonomic-matting', 'Anti-fatigue and ergonomic floor matting reducing operator strain at standing workstations. Bubble-top, diamond-plate and interlocking tile designs with bevelled edges, anti-slip surfaces and oil-resistant compounds.'),
  ('electrical-safety-insulation-matting', 'Electrical insulation matting per IS 15652 and IEC 61111 for switchboard and panel room safety. Class A to Class D voltage ratings up to 36 kV, anti-slip textures and fire-retardant grades in cut lengths and full rolls.'),
  ('skirt-board-conveyor-rubber', 'Skirt board rubber and conveyor accessories sealing transfer points and controlling spillage. Abrasion-resistant strips in 40 to 60 shore A, plus chevron lagging, impact bars and clamp systems for belt conveyor maintenance.'),
  ('rubber-o-ring-cord-stock', 'O-ring cord stock in NBR, EPDM, silicone and viton for making custom-size rings on site. Diameters from 1.5 to 25 mm in 70 and 90 shore grades, supplied per metre with splicing kits and adhesives.'),
  ('edge-trims-u-channels', 'Flexible edge trims and U-channels protecting panel edges and sealing enclosure doors. PVC and EPDM constructions with metal carriers, push-fit grip and co-extruded bulb options for automotive and cabinet work.'),
  ('d-strips-p-strips', 'D-section and P-section rubber strips for sealing doors, hatches and machine guards. Solid and sponge EPDM profiles with self-adhesive backing options, absorbing vibration and closing gaps from 3 to 20 mm.'),
  ('cylindrical-isolation-mounts', 'Cylindrical rubber-to-metal isolation mounts in male-male and male-female stud configurations. Natural rubber and neoprene elements from 8 to 75 mm diameter for isolating motors, pumps, compressors and instrumentation.'),
  ('vibration-isolation-pads', 'Ribbed and waffle-pattern vibration isolation pads for machinery installation without bolting. Layered rubber and cork-bonded constructions cutting structure-borne noise under presses, chillers, generators and HVAC plants.'),
  ('heavy-duty-machinery-mounts', 'Heavy-duty levelling and anti-vibration mounts for machine tools, injection moulders and presses. High load capacities with levelling screws, bonded rubber elements and oil-resistant compounds for precise, quiet installation.'),
  ('rubber-bushings-grommets', 'Rubber bushings and wiring grommets isolating vibration and protecting cables through panel holes. Standard and blind grommet profiles, plus bonded bushes for suspension links, in NBR, EPDM and silicone compounds.'),
  ('standard-o-rings-kits', 'Standard O-rings in metric and BS sizes with boxed assortment kits for maintenance teams. NBR 70, viton and silicone compounds covering popular sizes, with pick tools and size gauges for quick seal replacement.'),
  ('flange-gaskets', 'Flange gaskets in rubber, CAF, non-asbestos fibre and spiral-wound constructions. Full-face and ring-type patterns cut to IS, ANSI and DIN drilling, with graphite and PTFE options for steam and chemical duty.'),
  ('oil-seals-rotary-shaft-seals', 'Rotary shaft oil seals in single and double lip designs with spring-loaded sealing edges. Nitrile and viton compounds, metal-cased and rubber-covered ODs, in metric and inch sizes for gearboxes, pumps and axles.'),
  ('inflatable-custom-moulded-seals', 'Inflatable seals and custom moulded rubber parts manufactured to drawing. Silicone, EPDM and NBR compounds for autoclave doors, dryers and special machinery, with fabric reinforcement and metal inserts where required.'),
  ('suction-discharge-hose', 'Rubber suction and discharge hoses with spring-steel wire helix for water, slurry and oil transfer. Sizes from 25 to 300 mm with smooth bores, corrugated covers and built-in soft cuffs for coupling attachment.'),
  ('rubber-expansion-joints', 'Rubber expansion joints absorbing pipe movement, vibration and misalignment. Single and twin-sphere designs with floating flanges, EPDM and NBR bodies, and control rods for pump and chiller connections up to 600 mm.'),
  ('flexible-ducting', 'Flexible ducting for air, fume and dust extraction in PVC, PU and rubber constructions. Wire-reinforced walls, temperature grades to 150 degrees C, and abrasion-resistant PU for woodworking and pneumatic conveying.'),
  ('recessed-stem-bumpers', 'Recessed and stem-mount rubber bumpers absorbing impact on doors, gates and machinery. Push-in stems and through-hole designs in natural rubber and neoprene, protecting surfaces from repeated contact damage.'),
  ('adhesive-backed-bumper-pads', 'Self-adhesive rubber and polyurethane bumper pads in hemisphere, cylindrical and square profiles. Clear and black options from 6 to 25 mm diameter for cabinets, glass tops, electronics and point-of-sale fixtures.'),
  ('dock-bumpers', 'Loading dock bumpers protecting building structures and vehicle bodies during docking. Laminated, moulded and steel-faced designs with high energy absorption, supplied with fixings for bolt-on installation.'),
  ('end-caps-thread-protectors', 'Push-fit end caps and threaded protectors covering pipe ends, studs and fittings during transit and storage. LDPE, PVC and rubber options in metric and imperial sizes, from small electronics caps to large flange protectors.'),

  -- ── Vacuum Components ──────────────────────────────────────
  ('flat-suction-cups', 'Flat vacuum suction cups for handling sheets, glass, cartons and flat panels. Diameters from 5 to 200 mm in NBR, silicone and polyurethane, with ribbed faces for thin flexible workpieces and threaded fitting options.'),
  ('bellows-suction-cups', 'Single and multi-convolution bellows suction cups compensating for height differences and angled surfaces. Ideal for curved, textured and delicate parts, in food-grade silicone, NBR and wear-resistant PU compounds.'),
  ('oval-rectangular-suction-cups', 'Oval and rectangular suction cups maximising grip area on narrow and elongated workpieces. Flat and bellows profiles with support ribs for limp materials such as sheet metal strips, profiles and packaging.'),
  ('specialty-cups-grippers', 'Specialty vacuum cups and grippers for bags, eggs-style fragile parts, hot workpieces and oily sheets. High-temperature silicones, mark-free compounds and needle-gripper alternatives for porous textiles and composites.'),
  ('pneumatic-vacuum-ejectors-venturi', 'Compressed-air driven vacuum ejectors using the venturi principle with no moving parts. Single and multi-stage designs with vacuum levels to 90 percent, integrated silencers, and compact inline bodies for end-of-arm tooling.'),
  ('electric-rotary-vane-vacuum-pumps', 'Electric rotary vane vacuum pumps in oil-lubricated and dry-running versions. Capacities from 4 to 300 m3/hr with ultimate vacuum to 0.5 mbar, for packaging, thermoforming, hold-down and central supply duty.'),
  ('central-vacuum-stations', 'Central vacuum stations combining pumps, receivers and controls for plant-wide vacuum supply. Duplex configurations with automatic changeover, filtration and demand-based control reducing energy consumption.'),
  ('vacuum-solenoid-valves', 'Solenoid valves engineered for vacuum service with high conductance and low leakage. 2/2 and 3/2 functions for cup release and vacuum switching, in 24V DC and 230V AC coils with manual override.'),
  ('blow-off-fast-release-valves', 'Blow-off and quick-release valves shortening cycle times by actively venting vacuum cups. Adjustable blow-off flow for positive part release of thin sheets and sticky products in high-speed handling.'),
  ('vacuum-check-valves', 'Vacuum check and non-return valves maintaining grip during supply interruption. Spring and gravity designs preserving cup vacuum in multi-cup systems when individual cups miss the workpiece.'),
  ('vacuum-filters', 'Inline vacuum filters protecting ejectors, pumps and valves from dust and debris. Clear-bowl and metal-body designs with paper, sintered and washable elements in connection sizes from M5 to 2 inch.'),
  ('digital-vacuum-switches-sensors', 'Digital vacuum switches and sensors with LED displays, PNP/NPN outputs and analogue signals. Programmable setpoints and hysteresis for grip verification, leak detection and energy-saving vacuum control.'),
  ('analog-vacuum-gauges', 'Analogue dial vacuum gauges for local indication on vacuum systems. Bourdon and capsule movements in 40 to 100 mm dials, ranges from 0 to -760 mmHg, with panel-mount and inline connection options.'),
  ('area-gripping-systems-foam-pads', 'Area gripping systems with foam sealing pads handling varied part shapes without cup changeover. Integrated vacuum generation and check valves per cell, gripping full and partial layers for palletising and layer picking.'),
  ('robotic-end-effectors', 'Complete vacuum end-effectors for robots and cobots including mounting flanges, cup arrays and generators. Lightweight aluminium and carbon constructions, quick-change interfaces and configurable layouts for bin picking and packaging.')

) AS v(slug, description)
WHERE products.slug = v.slug;

-- ── Done: descriptions set for 103 products ──────────────────
-- Verify: SELECT slug, left(description, 60) FROM products ORDER BY category_slug, sort_order;
